# This is a basic workflow to help you get started with Actions

name: Comunicador de la legion

on:
  workflow_dispatch:
    inputs:
      villano:
        description: "¿Qué villano  envia el mensaje?"
        required: true
        type: choice
        options: 
          - Lex Luthor
          - Magneto
          - Jocker
      
      mensaje:
        description: "mensaje para el consejo" 
        required: true
        default: "La misión fue un éxito"


      prioridad:
        description: "¿Qué villano  envia el mensaje?"
        required: true
        type: choice
        options: 
          - 🔵 Baja
          - 🟢 Media
          - 🔴 Alta


jobs:

  transmitir-mensaje:

    runs-on: ubuntu-latest

    steps:
      - name: Imprimir inputs.
        run: |
          echo "Inputs: "
          echo ""
          echo "villano ${{ inputs.villano}}"
          echo "nivel ${{ inputs.prioridad}}"
          echo "mensaje ${{ inputs.mensaje}}"