name: Reclutamiento de Agente

on: push

job:
    reporte-de-reclutamiento:
        runs-one: ubuntu-latest

        steps:
            - name: El Agente se presenta
            run: echo "Soy Lex Luthor líder de la legión de mal"